# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main-window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1030, 689)
        MainWindow.setMinimumSize(QtCore.QSize(1030, 689))
        MainWindow.setMaximumSize(QtCore.QSize(1030, 689))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/flash-software-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.openGL_preview = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGL_preview.setMouseTracking(True)
        self.openGL_preview.setBackgroundColor(QtGui.QColor([155, 155, 155, 0]))
        self.openGL_preview.setFocusPolicy(QtCore.Qt.NoFocus)
        self.openGL_preview.setObjectName("openGL_preview")
        self.slider_layer = QtWidgets.QSlider(self.centralwidget)
        self.slider_layer.setGeometry(QtCore.QRect(580, 500, 22, 160))
        self.slider_layer.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.slider_layer.setOrientation(QtCore.Qt.Vertical)
        self.slider_layer.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_layer.setObjectName("slider_layer")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(610, 0, 421, 591))
        self.toolBox.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.toolBox.setObjectName("toolBox")
        self.page_fileproperties = QtWidgets.QWidget()
        self.page_fileproperties.setGeometry(QtCore.QRect(0, 0, 421, 510))
        self.page_fileproperties.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.page_fileproperties.setObjectName("page_fileproperties")
        self.label = QtWidgets.QLabel(self.page_fileproperties)
        self.label.setGeometry(QtCore.QRect(10, 0, 101, 31))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_filename = QtWidgets.QLabel(self.page_fileproperties)
        self.label_filename.setGeometry(QtCore.QRect(130, 0, 281, 31))
        self.label_filename.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_filename.setObjectName("label_filename")
        self.lcdNumber_instructions = QtWidgets.QLCDNumber(self.page_fileproperties)
        self.lcdNumber_instructions.setGeometry(QtCore.QRect(10, 80, 101, 31))
        self.lcdNumber_instructions.setObjectName("lcdNumber_instructions")
        self.lcdNumber_bricks = QtWidgets.QLCDNumber(self.page_fileproperties)
        self.lcdNumber_bricks.setGeometry(QtCore.QRect(10, 40, 101, 31))
        self.lcdNumber_bricks.setObjectName("lcdNumber_bricks")
        self.label_2 = QtWidgets.QLabel(self.page_fileproperties)
        self.label_2.setGeometry(QtCore.QRect(120, 40, 291, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.page_fileproperties)
        self.label_3.setGeometry(QtCore.QRect(120, 80, 291, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_printfile = QtWidgets.QPushButton(self.page_fileproperties)
        self.pushButton_printfile.setEnabled(True)
        self.pushButton_printfile.setGeometry(QtCore.QRect(10, 470, 401, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_printfile.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_printfile.setFont(font)
        self.pushButton_printfile.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.pushButton_printfile.setObjectName("pushButton_printfile")
        self.groupBox_filedescription = QtWidgets.QGroupBox(self.page_fileproperties)
        self.groupBox_filedescription.setGeometry(QtCore.QRect(10, 120, 401, 121))
        self.groupBox_filedescription.setObjectName("groupBox_filedescription")
        self.label_filedescription = QtWidgets.QLabel(self.groupBox_filedescription)
        self.label_filedescription.setGeometry(QtCore.QRect(10, 20, 381, 91))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setItalic(True)
        self.label_filedescription.setFont(font)
        self.label_filedescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_filedescription.setObjectName("label_filedescription")
        self.toolBox.addItem(self.page_fileproperties, "")
        self.page_printproperties = QtWidgets.QWidget()
        self.page_printproperties.setGeometry(QtCore.QRect(0, 0, 421, 510))
        self.page_printproperties.setObjectName("page_printproperties")
        self.groupBox_baseplate = QtWidgets.QGroupBox(self.page_printproperties)
        self.groupBox_baseplate.setGeometry(QtCore.QRect(10, 0, 401, 131))
        self.groupBox_baseplate.setObjectName("groupBox_baseplate")
        self.spinBox_baseplate_size_x = QtWidgets.QSpinBox(self.groupBox_baseplate)
        self.spinBox_baseplate_size_x.setGeometry(QtCore.QRect(10, 40, 161, 22))
        self.spinBox_baseplate_size_x.setProperty("value", 10)
        self.spinBox_baseplate_size_x.setObjectName("spinBox_baseplate_size_x")
        self.label_4 = QtWidgets.QLabel(self.groupBox_baseplate)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 381, 16))
        self.label_4.setObjectName("label_4")
        self.spinBox_baseplate_size_y = QtWidgets.QSpinBox(self.groupBox_baseplate)
        self.spinBox_baseplate_size_y.setGeometry(QtCore.QRect(10, 70, 161, 22))
        self.spinBox_baseplate_size_y.setProperty("value", 10)
        self.spinBox_baseplate_size_y.setObjectName("spinBox_baseplate_size_y")
        self.spinBox_baseplate_size_z = QtWidgets.QSpinBox(self.groupBox_baseplate)
        self.spinBox_baseplate_size_z.setGeometry(QtCore.QRect(10, 100, 161, 22))
        self.spinBox_baseplate_size_z.setProperty("value", 10)
        self.spinBox_baseplate_size_z.setObjectName("spinBox_baseplate_size_z")
        self.label_5 = QtWidgets.QLabel(self.groupBox_baseplate)
        self.label_5.setGeometry(QtCore.QRect(180, 40, 47, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_baseplate)
        self.label_6.setGeometry(QtCore.QRect(180, 70, 47, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_baseplate)
        self.label_7.setGeometry(QtCore.QRect(180, 100, 211, 21))
        self.label_7.setObjectName("label_7")
        self.groupBox_print = QtWidgets.QGroupBox(self.page_printproperties)
        self.groupBox_print.setGeometry(QtCore.QRect(10, 140, 401, 221))
        self.groupBox_print.setObjectName("groupBox_print")
        self.dial_printspeed = QtWidgets.QDial(self.groupBox_print)
        self.dial_printspeed.setGeometry(QtCore.QRect(10, 20, 50, 51))
        self.dial_printspeed.setMinimum(10)
        self.dial_printspeed.setMaximum(35)
        self.dial_printspeed.setPageStep(5)
        self.dial_printspeed.setOrientation(QtCore.Qt.Horizontal)
        self.dial_printspeed.setNotchTarget(5.0)
        self.dial_printspeed.setNotchesVisible(True)
        self.dial_printspeed.setObjectName("dial_printspeed")
        self.label_printspeed = QtWidgets.QLabel(self.groupBox_print)
        self.label_printspeed.setGeometry(QtCore.QRect(70, 20, 47, 51))
        self.label_printspeed.setObjectName("label_printspeed")
        self.label_8 = QtWidgets.QLabel(self.groupBox_print)
        self.label_8.setGeometry(QtCore.QRect(120, 20, 271, 51))
        self.label_8.setObjectName("label_8")
        self.dial_zhop = QtWidgets.QDial(self.groupBox_print)
        self.dial_zhop.setGeometry(QtCore.QRect(10, 80, 50, 51))
        self.dial_zhop.setMinimum(5)
        self.dial_zhop.setMaximum(50)
        self.dial_zhop.setSingleStep(5)
        self.dial_zhop.setNotchTarget(5.0)
        self.dial_zhop.setNotchesVisible(True)
        self.dial_zhop.setObjectName("dial_zhop")
        self.label_zhop = QtWidgets.QLabel(self.groupBox_print)
        self.label_zhop.setGeometry(QtCore.QRect(70, 80, 47, 51))
        self.label_zhop.setObjectName("label_zhop")
        self.label_9 = QtWidgets.QLabel(self.groupBox_print)
        self.label_9.setGeometry(QtCore.QRect(120, 80, 271, 51))
        self.label_9.setObjectName("label_9")
        self.dial_presspower = QtWidgets.QDial(self.groupBox_print)
        self.dial_presspower.setGeometry(QtCore.QRect(10, 140, 50, 51))
        self.dial_presspower.setMinimum(10)
        self.dial_presspower.setMaximum(100)
        self.dial_presspower.setSingleStep(5)
        self.dial_presspower.setPageStep(10)
        self.dial_presspower.setOrientation(QtCore.Qt.Horizontal)
        self.dial_presspower.setNotchTarget(10.0)
        self.dial_presspower.setNotchesVisible(True)
        self.dial_presspower.setObjectName("dial_presspower")
        self.label_presspower = QtWidgets.QLabel(self.groupBox_print)
        self.label_presspower.setGeometry(QtCore.QRect(70, 140, 47, 51))
        self.label_presspower.setObjectName("label_presspower")
        self.label_10 = QtWidgets.QLabel(self.groupBox_print)
        self.label_10.setGeometry(QtCore.QRect(120, 140, 271, 51))
        self.label_10.setObjectName("label_10")
        self.toolBox.addItem(self.page_printproperties, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setEnabled(False)
        self.page_3.setGeometry(QtCore.QRect(0, 0, 421, 510))
        self.page_3.setObjectName("page_3")
        self.toolBox.addItem(self.page_3, "")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(620, 600, 401, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.label_printtime = QtWidgets.QLabel(self.centralwidget)
        self.label_printtime.setGeometry(QtCore.QRect(620, 641, 401, 20))
        self.label_printtime.setObjectName("label_printtime")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(-10, 10, 101, 121))
        self.label_logo.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap(":/logo/flash-software-128.png"))
        self.label_logo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_logo.setObjectName("label_logo")
        self.label_secondstatus = QtWidgets.QLabel(self.centralwidget)
        self.label_secondstatus.setGeometry(QtCore.QRect(620, 621, 401, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_secondstatus.setFont(font)
        self.label_secondstatus.setObjectName("label_secondstatus")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1030, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionConvert = QtWidgets.QAction(MainWindow)
        self.actionConvert.setObjectName("actionConvert")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionConvert)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0  )
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Team Lightning FLASH Software"))
        self.slider_layer.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Layer</span></p><p>Select which layer to preview. Put slider to the bottom to view all layers.</p></body></html>"))
        self.slider_layer.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Layer</span></p><p>Select which layer to preview. Put slider to the bottom to view all layers.</p></body></html>"))
        self.label.setText(_translate("MainWindow", "File Name"))
        self.label_filename.setText(_translate("MainWindow", "File Name Here"))
        self.label_2.setText(_translate("MainWindow", "Number of Bricks"))
        self.label_3.setText(_translate("MainWindow", "Number of instructions"))
        self.pushButton_printfile.setText(_translate("MainWindow", "Print File"))
        self.groupBox_filedescription.setTitle(_translate("MainWindow", "File Description"))
        self.label_filedescription.setText(_translate("MainWindow", "File Description from model file"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_fileproperties), _translate("MainWindow", "File Properties"))
        self.groupBox_baseplate.setTitle(_translate("MainWindow", "Baseplate"))
        self.spinBox_baseplate_size_x.setSuffix(_translate("MainWindow", " studs"))
        self.label_4.setText(_translate("MainWindow", "Enter the maximum building sizes"))
        self.spinBox_baseplate_size_y.setSuffix(_translate("MainWindow", " studs"))
        self.spinBox_baseplate_size_z.setSuffix(_translate("MainWindow", " studs"))
        self.label_5.setText(_translate("MainWindow", "X-axis"))
        self.label_6.setText(_translate("MainWindow", "Y-axis"))
        self.label_7.setText(_translate("MainWindow", "Z-axis (maximum build height)"))
        self.groupBox_print.setTitle(_translate("MainWindow", "Print"))
        self.label_printspeed.setText(_translate("MainWindow", "10%"))
        self.label_8.setText(_translate("MainWindow", "Printing speed"))
        self.label_zhop.setText(_translate("MainWindow", "1 stud"))
        self.label_9.setText(_translate("MainWindow", "Z-hop"))
        self.label_presspower.setText(_translate("MainWindow", "10%"))
        self.label_10.setText(_translate("MainWindow", "Brick Press Power"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_printproperties), _translate("MainWindow", "Printer Properties"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Material Properties"))
        self.label_status.setText(_translate("MainWindow", "Status Message"))
        self.label_printtime.setText(_translate("MainWindow", "Estimated Print Time: "))
        self.label_secondstatus.setText(_translate("MainWindow", "Secondary Status Message"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionConvert.setText(_translate("MainWindow", "Convert"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

import ui_resource
